export const AIRPORTS_CODES: { iata: string; name: { ru: string; en: string } }[] = [
  { iata: 'ACE', name: { ru: 'Лансароте', en: 'Lanzarote' } },
  { iata: 'ADB', name: { ru: 'Измир', en: 'Izmir' } },
  { iata: 'AGP', name: { ru: 'Малага', en: 'Malaga' } },
  { iata: 'ALC', name: { ru: 'Аликанте', en: 'Alicante' } },
  { iata: 'AMM', name: { ru: 'Амман', en: 'Amman' } },
  { iata: 'AMS', name: { ru: 'Амстердам', en: 'Amsterdam' } },
  { iata: 'ARN', name: { ru: 'Стокгольм', en: 'Stockholm' } },
  { iata: 'ATH', name: { ru: 'Афины', en: 'Athens' } },
  { iata: 'AUH', name: { ru: 'Абу-Даби', en: 'Abu Dhabi' } },
  { iata: 'AYT', name: { ru: 'Анталья', en: 'Antalya' } },
  { iata: 'BAH', name: { ru: 'Манама', en: 'Manama' } },
  { iata: 'BCN', name: { ru: 'Барселона', en: 'Barcelona' } },
  { iata: 'BEG', name: { ru: 'Белград', en: 'Belgrade' } },
  { iata: 'BER', name: { ru: 'Берлин', en: 'Berlin' } },
  { iata: 'BEY', name: { ru: 'Бейрут', en: 'Beirut' } },
  { iata: 'BFS', name: { ru: 'Белфаст', en: 'Belfast' } },
  { iata: 'BGO', name: { ru: 'Берген', en: 'Bergen' } },
  { iata: 'BJV', name: { ru: 'Бодрум', en: 'Bodrum' } },
  { iata: 'BOD', name: { ru: 'Бордо', en: 'Bordeaux' } },
  { iata: 'BOJ', name: { ru: 'Бургас', en: 'Burgas' } },
  { iata: 'BRE', name: { ru: 'Бремен', en: 'Bremen' } },
  { iata: 'BRI', name: { ru: 'Бари', en: 'Bari' } },
  { iata: 'BRQ', name: { ru: 'Брно', en: 'Brno' } },
  { iata: 'BRU', name: { ru: 'Брюссель', en: 'Brussels' } },
  { iata: 'BTS', name: { ru: 'Братислава', en: 'Bratislava' } },
  { iata: 'BUD', name: { ru: 'Будапешт', en: 'Budapest' } },
  { iata: 'VCE', name: { ru: 'Венеция', en: 'Venice' } },
  { iata: 'CAI', name: { ru: 'Каир', en: 'Cairo' } },
  { iata: 'CDG', name: { ru: 'Париж (Шарль-де-Голль)', en: 'Paris (Charles de Gaulle)' } },
  { iata: 'CFU', name: { ru: 'Корфу', en: 'Corfu' } },
  { iata: 'CGN', name: { ru: 'Кёльн', en: 'Cologne' } },
  { iata: 'CIA', name: { ru: 'Рим (Чампино)', en: 'Rome (Ciampino)' } },
  { iata: 'CLJ', name: { ru: 'Клуж-Напока', en: 'Cluj-Napoca' } },
  { iata: 'CMN', name: { ru: 'Касабланка', en: 'Casablanca' } },
  { iata: 'CPH', name: { ru: 'Копенгаген', en: 'Copenhagen' } },
  { iata: 'CRA', name: { ru: 'Крайова', en: 'Craiova' } },
  { iata: 'CRL', name: { ru: 'Брюссель (Шарлеруа)', en: 'Brussels (Charleroi)' } },
  { iata: 'CTA', name: { ru: 'Катания', en: 'Catania' } },
  { iata: 'DBV', name: { ru: 'Дубровник', en: 'Dubrovnik' } },
  { iata: 'DLM', name: { ru: 'Даламан', en: 'Dalaman' } },
  { iata: 'DME', name: { ru: 'Москва (Домодедово)', en: 'Moscow (Domodedovo)' } },
  { iata: 'DOH', name: { ru: 'Доха', en: 'Doha' } },
  { iata: 'DRS', name: { ru: 'Дрезден', en: 'Dresden' } },
  { iata: 'DUS', name: { ru: 'Дюссельдорф', en: 'Dusseldorf' } },
  { iata: 'DXB', name: { ru: 'Дубай', en: 'Dubai' } },
  { iata: 'EDI', name: { ru: 'Эдинбург', en: 'Edinburgh' } },
  { iata: 'EIN', name: { ru: 'Эйндховен', en: 'Eindhoven' } },
  { iata: 'ESB', name: { ru: 'Анкара', en: 'Ankara' } },
  { iata: 'EVN', name: { ru: 'Ереван', en: 'Yerevan' } },
  { iata: 'FAO', name: { ru: 'Фару', en: 'Faro' } },
  { iata: 'FCO', name: { ru: 'Рим (Фьюмичино)', en: 'Rome (Fiumicino)' } },
  { iata: 'FNC', name: { ru: 'Фуншал', en: 'Funchal' } },
  { iata: 'FRA', name: { ru: 'Франкфурт', en: 'Frankfurt' } },
  { iata: 'FUE', name: { ru: 'Фуэртевентура', en: 'Fuerteventura' } },
  { iata: 'GDN', name: { ru: 'Гданьск', en: 'Gdansk' } },
  { iata: 'GOT', name: { ru: 'Гётеборг', en: 'Gothenburg' } },
  { iata: 'GVA', name: { ru: 'Женева', en: 'Geneva' } },
  { iata: 'GYD', name: { ru: 'Баку', en: 'Baku' } },
  { iata: 'HAJ', name: { ru: 'Ганновер', en: 'Hannover' } },
  { iata: 'HAM', name: { ru: 'Гамбург', en: 'Hamburg' } },
  { iata: 'HEL', name: { ru: 'Хельсинки', en: 'Helsinki' } },
  { iata: 'HER', name: { ru: 'Ираклион', en: 'Heraklion' } },
  { iata: 'HRG', name: { ru: 'Хургада', en: 'Hurghada' } },
  { iata: 'IAS', name: { ru: 'Яссы', en: 'Iasi' } },
  { iata: 'IBZ', name: { ru: 'Ибица', en: 'Ibiza' } },
  { iata: 'INI', name: { ru: 'Ниш', en: 'Nis' } },
  { iata: 'IST', name: { ru: 'Стамбул', en: 'Istanbul' } },
  { iata: 'JED', name: { ru: 'Джидда', en: 'Jeddah' } },
  { iata: 'JTR', name: { ru: 'Санторини', en: 'Santorini' } },
  { iata: 'KBP', name: { ru: 'Киев', en: 'Kyiv' } },
  { iata: 'KIV', name: { ru: 'Кишинев', en: 'Chisinau' } },
  { iata: 'KRK', name: { ru: 'Краков', en: 'Krakow' } },
  { iata: 'KRR', name: { ru: 'Краснодар', en: 'Krasnodar' } },
  { iata: 'KSC', name: { ru: 'Кошице', en: 'Kosice' } },
  { iata: 'KTW', name: { ru: 'Катовице', en: 'Katowice' } },
  { iata: 'KUN', name: { ru: 'Каунас', en: 'Kaunas' } },
  { iata: 'KUT', name: { ru: 'Кутаиси', en: 'Kutaisi' } },
  { iata: 'KWI', name: { ru: 'Эль-Кувейт', en: 'Kuwait City' } },
  { iata: 'KZN', name: { ru: 'Казань', en: 'Kazan' } },
  { iata: 'LCA', name: { ru: 'Ларнака', en: 'Larnaca' } },
  { iata: 'LED', name: { ru: 'Санкт-Петербург', en: 'Saint Petersburg' } },
  { iata: 'LEJ', name: { ru: 'Лейпциг', en: 'Leipzig' } },
  { iata: 'LGW', name: { ru: 'Лондон (Гатвик)', en: 'London (Gatwick)' } },
  { iata: 'LIS', name: { ru: 'Лиссабон', en: 'Lisbon' } },
  { iata: 'LJU', name: { ru: 'Любляна', en: 'Ljubljana' } },
  { iata: 'LPA', name: { ru: 'Гран-Канария', en: 'Gran Canaria' } },
  { iata: 'LPL', name: { ru: 'Ливерпуль', en: 'Liverpool' } },
  { iata: 'LTN', name: { ru: 'Лондон (Лутон)', en: 'London (Luton)' } },
  { iata: 'LUZ', name: { ru: 'Люблин', en: 'Lublin' } },
  { iata: 'LWO', name: { ru: 'Львов', en: 'Lviv' } },
  { iata: 'MAD', name: { ru: 'Мадрид', en: 'Madrid' } },
  { iata: 'MCT', name: { ru: 'Маскат', en: 'Muscat' } },
  { iata: 'MLA', name: { ru: 'Мальта', en: 'Malta' } },
  { iata: 'MOW', name: { ru: 'Москва', en: 'Moscow' } },
  { iata: 'MRS', name: { ru: 'Марсель', en: 'Marseille' } },
  { iata: 'MSQ', name: { ru: 'Минск', en: 'Minsk' } },
  { iata: 'MUC', name: { ru: 'Мюнхен', en: 'Munich' } },
  { iata: 'MXP', name: { ru: 'Милан', en: 'Milan' } },
  { iata: 'NAP', name: { ru: 'Неаполь', en: 'Naples' } },
  { iata: 'NCE', name: { ru: 'Ницца', en: 'Nice' } },
  { iata: 'NUE', name: { ru: 'Нюрнберг', en: 'Nuremberg' } },
  { iata: 'ODS', name: { ru: 'Одесса', en: 'Odessa' } },
  { iata: 'OPO', name: { ru: 'Порту', en: 'Porto' } },
  { iata: 'ORY', name: { ru: 'Париж', en: 'Paris' } },
  { iata: 'OSL', name: { ru: 'Осло', en: 'Oslo' } },
  { iata: 'OTP', name: { ru: 'Бухарест', en: 'Bucharest' } },
  { iata: 'PDL', name: { ru: 'Понта-Делгада', en: 'Ponta Delgada' } },
  { iata: 'PFO', name: { ru: 'Пафос', en: 'Paphos' } },
  { iata: 'PLQ', name: { ru: 'Паланга', en: 'Palanga' } },
  { iata: 'PMI', name: { ru: 'Пальма-де-Майорка', en: 'Palma de Mallorca' } },
  { iata: 'PMO', name: { ru: 'Палермо', en: 'Palermo' } },
  { iata: 'POZ', name: { ru: 'Познань', en: 'Poznan' } },
  { iata: 'PRG', name: { ru: 'Прага', en: 'Prague' } },
  { iata: 'PRN', name: { ru: 'Приштина', en: 'Pristina' } },
  { iata: 'PUY', name: { ru: 'Пула', en: 'Pula' } },
  { iata: 'RAK', name: { ru: 'Марракеш', en: 'Marrakesh' } },
  { iata: 'RHO', name: { ru: 'Родос', en: 'Rhodes' } },
  { iata: 'RIX', name: { ru: 'Рига', en: 'Riga' } },
  { iata: 'RUH', name: { ru: 'Эр-Рияд', en: 'Riyadh' } },
  { iata: 'RZE', name: { ru: 'Жешув', en: 'Rzeszow' } },
  { iata: 'SAW', name: { ru: 'Стамбул (Сабиха Гекчен)', en: 'Istanbul (Sabiha Gokcen)' } },
  { iata: 'SBZ', name: { ru: 'Сибиу', en: 'Sibiu' } },
  { iata: 'SJJ', name: { ru: 'Сараево', en: 'Sarajevo' } },
  { iata: 'SKG', name: { ru: 'Салоники', en: 'Thessaloniki' } },
  { iata: 'SKP', name: { ru: 'Скопье', en: 'Skopje' } },
  { iata: 'SOF', name: { ru: 'София', en: 'Sofia' } },
  { iata: 'SPU', name: { ru: 'Сплит', en: 'Split' } },
  { iata: 'SSH', name: { ru: 'Шарм-эль-Шейх', en: 'Sharm El Sheikh' } },
  { iata: 'STR', name: { ru: 'Штутгарт', en: 'Stuttgart' } },
  { iata: 'SVO', name: { ru: 'Москва (Шереметьево)', en: 'Moscow (Sheremetyevo)' } },
  { iata: 'SVX', name: { ru: 'Екатеринбург', en: 'Yekaterinburg' } },
  { iata: 'TBS', name: { ru: 'Тбилиси', en: 'Tbilisi' } },
  { iata: 'TFS', name: { ru: 'Тенерифе', en: 'Tenerife' } },
  { iata: 'TGD', name: { ru: 'Подгорица', en: 'Podgorica' } },
  { iata: 'TIA', name: { ru: 'Тирана', en: 'Tirana' } },
  { iata: 'TKU', name: { ru: 'Турку', en: 'Turku' } },
  { iata: 'TLL', name: { ru: 'Таллин', en: 'Tallinn' } },
  { iata: 'TLV', name: { ru: 'Тель-Авив', en: 'Tel Aviv' } },
  { iata: 'TRD', name: { ru: 'Тронхейм', en: 'Trondheim' } },
  { iata: 'TSR', name: { ru: 'Тимишоара', en: 'Timisoara' } },
  { iata: 'VAR', name: { ru: 'Варна', en: 'Varna' } },
  { iata: 'VCE', name: { ru: 'Венеция', en: 'Venice' } },
  { iata: 'VIE', name: { ru: 'Вена', en: 'Vienna' } },
  { iata: 'VKO', name: { ru: 'Москва (Внуково)', en: 'Moscow (Vnukovo)' } },
  { iata: 'VNO', name: { ru: 'Вильнюс', en: 'Vilnius' } },
  { iata: 'WAW', name: { ru: 'Варшава', en: 'Warsaw' } },
  { iata: 'WRO', name: { ru: 'Вроцлав', en: 'Wroclaw' } },
  { iata: 'ZAD', name: { ru: 'Задар', en: 'Zadar' } },
  { iata: 'ZAG', name: { ru: 'Загреб', en: 'Zagreb' } },
  { iata: 'ZRH', name: { ru: 'Цюрих', en: 'Zurich' } },
];
